title: Machine Learning Workshop @sofatutor
description: {The base for all our different activities troughout the workshop. 
- Part 1: [link](Pages/part1.md)
- Part 2: [link](Pages/part2.md)
- Part 3: [link](Pages/part3.md)
- Part 4: [link](Pages/part4.md)}
theme: jekyll-theme-minimal